// Shared icon set, backed by Phosphor (duotone). Consumers use Icons.<name>;
// sizing/colour come from the surrounding CSS (svg inherits currentColor).
import {
  User,
  CalendarBlank,
  CurrencyDollar,
  MapPin,
  CheckSquare,
  Plus,
  Clock,
  BookmarkSimple,
  Briefcase,
  Wallet,
  MagnifyingGlass,
  EnvelopeSimple,
  Bell,
  SignOut,
  Sparkle,
  UploadSimple,
  GraduationCap,
  Certificate,
  CheckCircle,
  Wrench,
  Broom,
  Lightning,
  Hammer,
  DeviceMobile,
  Truck,
  Quotes,
  ChatCircle,
  Phone,
  X,
  DotsThree,
  PaperPlaneTilt,
  Sun,
  Moon,
  Gear,
  ShieldCheck,
  ThumbsUp,
  ThumbsDown,
  SquaresFour,
  IdentificationCard,
  Camera,
  WarningCircle,
  Scales,
} from '@phosphor-icons/react';

const w = 'regular';

export const Icons = {
  user: <User weight={w} />,
  calendar: <CalendarBlank weight={w} />,
  dollar: <CurrencyDollar weight={w} />,
  pin: <MapPin weight={w} />,
  check: <CheckSquare weight={w} />,
  plus: <Plus weight={w} />,
  clock: <Clock weight={w} />,
  bookmark: <BookmarkSimple weight={w} />,
  briefcase: <Briefcase weight={w} />,
  wallet: <Wallet weight={w} />,
  search: <MagnifyingGlass weight={w} />,
  mail: <EnvelopeSimple weight={w} />,
  bell: <Bell weight={w} />,
  logout: <SignOut weight={w} />,
  spark: <Sparkle weight={w} />,
  upload: <UploadSimple weight={w} />,
  graduation: <GraduationCap weight="fill" />,
  certificate: <Certificate weight="fill" />,
  checkCircle: <CheckCircle weight="fill" />,
  wrench: <Wrench weight={w} />,
  broom: <Broom weight={w} />,
  lightning: <Lightning weight={w} />,
  hammer: <Hammer weight={w} />,
  device: <DeviceMobile weight={w} />,
  truck: <Truck weight={w} />,
  quote: <Quotes weight="fill" />,
  chat: <ChatCircle weight={w} />,
  phone: <Phone weight="fill" />,
  close: <X weight="bold" />,
  dots: <DotsThree weight="bold" />,
  send: <PaperPlaneTilt weight="fill" />,
  sun: <Sun weight="fill" />,
  moon: <Moon weight="fill" />,
  settings: <Gear weight={w} />,
  shield: <ShieldCheck weight={w} />,
  thumbsUp: <ThumbsUp weight={w} />,
  thumbsDown: <ThumbsDown weight={w} />,
  grid: <SquaresFour weight={w} />,
  idCard: <IdentificationCard weight={w} />,
  camera: <Camera weight={w} />,
  warning: <WarningCircle weight="fill" />,
  scales: <Scales weight={w} />,
};
